jobs:
  test:
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: ./.github/workflows/test.yaml
name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '**' ]
